[package]
name = "zed-statamic-antlers"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zed_extension_api = "0.5.0"

[lib]
crate-type = ["cdylib"]
